# Training configuration for hip-hop mixer

# Default training parameters
default:
  num_epochs: 5
  batch_size: 4
  learning_rate: 5.0e-5
  weight_decay: 0.01
  gradient_accumulation_steps: 4
  fp16: true
  save_strategy: "epoch"
  save_total_limit: 2
  logging_steps: 10
  report_to: ["tensorboard"]

# Models directory configuration
models_dir: "models/finetuned/mixer"  # Directory for storing mixer models (relative to project root)

# Data configuration
data:
  segment_duration: 5.0  # Duration of audio segments in seconds
  max_seq_len: 64        # Maximum sequence length for tokenized outputs
  sample_rate: 44100     # Target sample rate for audio
  
  # Specifying which stem types to include (vocals excluded for instrumental beats)
  stems:
    - "drums"
    - "bass"
    - "other"

# Mixer model configuration
mixer:
  mistral_model: "mistralai/Mistral-7B-v0.3"
  text_model: "bert-base-uncased"
  
  # Special tokens for the mixer operations
  special_tokens:
    - "loop"
    - "apply_eq" 
    - "apply_reverb"
    - "apply_delay"
    - "change_volume"
    - "pan"
    - "apply_low_pass"
    - "apply_high_pass"
    - "apply_normalize"
    - "apply_compression"
    - "trim"
    - "duplicate_and_shift"
    - "overlay_with"
    # Generation tools (not used in training yet)
    - "generate_melody"
    - "generate_drums"
    - "generate_bass"
    # Stem types (excluding vocals)
    - "stem=drums"
    - "stem=bass"
    - "stem=other"

# Generator integration settings
generators:
  melody:
    model_name: "facebook/musicgen-melody"
  bass:
    model_name: "facebook/musicgen-small"
  drums:
    model_name: "facebook/musicgen-small"

# Augmentation settings
augmentation:
  min_operations: 1
  max_operations: 4
  operations:
    loop:
      probability: 0.2
      params:
        loop_lengths: [4, 8]  # In beats
        counts: [2, 3, 4]
    apply_eq:
      probability: 0.3
      params:
        gain_range: [-6, 6]  # In dB
    apply_reverb:
      probability: 0.15
    apply_delay:
      probability: 0.15
      params:
        delay_ms: [100, 150, 200, 250, 300]
        decay_range: [0.3, 0.7]
    change_volume:
      probability: 0.2
      params:
        db_range: [-3, 3]
    pan:
      probability: 0.1
      params:
        pan_range: [-0.5, 0.5]
    apply_low_pass:
      probability: 0.1
      params:
        cutoffs: [500, 800, 1000, 1500, 2000]
    apply_high_pass:
      probability: 0.1
      params:
        cutoffs: [100, 150, 200, 300, 400]
    apply_normalize:
      probability: 0.1
    apply_compression:
      probability: 0.15
      params:
        threshold_range: [-30, -10]
        ratio_range: [2, 6] 